services:
  - type: web
    name: convocation-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y libreoffice
    startCommand: gunicorn app:app --timeout 120